name: JXCivilizations
version: 1.0.0
main: com.justxale.civilizations.Civilizations
description: Commands plugin for Civilizations MM event
author: justxale
website: https://papermc.io
api-version: '1.20'

permissions:
  permission.node:
    description: "Hi, LilAxolly"
    default: op

commands:
  event:
    description: "JXCivilizations Event manager"
    usage: "/event [start|add|end] [exploring|election|building|meeting|war]"
    permission: permission.node
    permission-message: "You do not have permission to use this command"
  leader:
    description: "Command to set leaders"
    usage: "/leader <player>"
    permission: permission.node
    permission-message: "You do not have permission to use this command"